### ISSUE TITLE
problem about cuhk02

### ISSUE THREAD

**Issue by CTC8901228** [vimar-gu/ColorPromptReID#1]
Hello,
The link of cuhk02 cuhk03 seems to be some problem. Can you kindly send the dataset to this email: dave983111@gmail.com  ?I'm a student of National Taiwan University.

**Comment by vimar-gu** [comment]
Hi! Thanks for your attention to this work. 
You can try contacting with the authors of CUHK02/03 to achieve the datasets.

**Comment by CTC8901228** [comment]
Hello,
May I ask you when and who do you contact the author? I have sent mail to
***@***.***  and ***@***.*** , but they don't respond me. I
think maybe I found the wrong email address.

Best regards,
Chiung-Tao

Jianyang Gu ***@***.***> 於 2023年10月15日 週日 上午11:06寫道：
